---

- src: openmicroscopy.postgresql
  version: 3.0.1

- src: openmicroscopy.omero-server
  version: 2.0.5

- name: openmicroscopy.omero-web
  src: https://github.com/manics/ansible-role-omero-web/archive/nginx-config-order.tar.gz
  version: nginx-config-order
